### ISSUE TITLE
Can not work properly with the plugins in "jnr_locopack"

### ISSUE THREAD

**Issue by njfdCRH1A** [magicant/bve-plugin-bridge#3]
I followed the instructions and found that the plugins was not working properly

**Comment by magicant** [comment]
Thanks for the info.

```
>C:\Users\magicant\Documents\BveTs\Scenarios\jnr_locopack\plugins\66_atsa.exe
Failed to load the Load function
```

**Comment by magicant** [comment]
[Version 2](https://github.com/magicant/bve-plugin-bridge/releases/tag/v2) should fix the issue. Please re-open if the issue persists for you. Thanks!
