### ISSUE TITLE
AtsArrayExtenderに対応しない

### ISSUE THREAD

**Issue by susLine2320** [magicant/bve-plugin-bridge#4]
お世話になっております。ろくらいんと申します。
このプラグインはAtsArrayExtenderに対応しておらず、２５５までの値しか変換されません。そのため、以下のコードに修正してコンパイルしてみたのですが、結局使用できませんでした。
もし可能であればこのコードを修正のうえ、アップしていただくことは可能でしょうか？
何卒ご検討のほどよろしくお願いします。
[frontend.zip](https://github.com/magicant/bve-plugin-bridge/files/14382579/frontend.zip)

**Comment by magicant** [comment]
とりあえずこうすれば動くんじゃないかなということで作ってみました。一切動作確認をしていないのですが……
[bve-plugin-bridge-v2+1024.zip](https://github.com/magicant/bve-plugin-bridge/files/14391660/bve-plugin-bridge-v2%2B1024.zip)

コードは [master+1024](https://github.com/magicant/bve-plugin-bridge/compare/master+1024) ブランチにあります

**Comment by susLine2320** [comment]
ありがとうございます。
試してみたのですが、いったんシナリオが立ち上がったのちすぐにフリーズするという動作をしました。一瞬のうちに見た感じ作動はしているようです。
環境としては、AtsEXインプットデバイス版のArrayExtenderで確認しています。

**Comment by susLine2320** [comment]
時間が経過し、再度試してみたのですがやはりダメそうでした。原因があまりわからないのですが再度調査いただくことはできますでしょうか？

**Comment by magicant** [comment]
私の方で調べてみますのでもう少しお待ちください

**Comment by magicant** [comment]
とりあえず手元でそれっぽい原因をつぶすことはできたんですが、 25 FPS 位しか出なくて抜本的に効率化すべきか考えているところです

**Comment by magicant** [comment]
リリース用ビルドだとそこまで遅くなそうなのでそのままリリースすることにします

**Comment by magicant** [comment]
@susLine2320 v3 をリリースしました。お試しください。
https://github.com/magicant/bve-plugin-bridge/releases/tag/v3
